//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprotify_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artiest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artiest()
        {
            this.AlbumArtiesten = new HashSet<AlbumArtiest>();
            this.ArtiestNummers = new HashSet<ArtiestNummer>();
        }
    
        public int id { get; set; }
        public Nullable<bool> verified { get; set; }
        public int maandelijkseLuisteraars { get; set; }
        public string naam { get; set; }
        public Nullable<bool> follow { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumArtiest> AlbumArtiesten { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtiestNummer> ArtiestNummers { get; set; }
    }
}
