//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprotify_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gebruiker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gebruiker()
        {
            this.Comments = new HashSet<Comment>();
            this.PlaylistGebruikers = new HashSet<PlaylistGebruiker>();
        }
    
        public int id { get; set; }
        public string naam { get; set; }
        public string achternaam { get; set; }
        public string emailadres { get; set; }
        public decimal telefoonnummer { get; set; }
        public System.DateTime geboortedatum { get; set; }
        public string wachtwoord { get; set; }
        public string geslacht { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaylistGebruiker> PlaylistGebruikers { get; set; }
    }
}
