//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprotify_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NummerGenre
    {
        public int id { get; set; }
        public int nummerId { get; set; }
        public int genreId { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Nummer Nummer { get; set; }
    }
}
